on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: Ubuntu-latest

    steps:
      - name: "Listing all the files"
        run: ls

      - uses: actions/checkout@v3
      - name: "Listing all the files"
        run: ls

      - name: "Image building"
        run: docker build -t ertre .

